routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GalleryController@index');

# Disable registration
Auth::routes(['register' => false]); 

Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function () {
    Route::get('/', function () { return redirect()->route('gallery.index'); });
    Route::resource('gallery', 'Admin\GalleryCategoryController');
//    Route::apiResource('gallery', 'Admin\GalleryCategoryController');
});

//Route::get('/home', 'HomeController@index')->name('home');

app/GalleryCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class GalleryCategory extends Model
{
    protected $fillable = [
        'name',
        'description'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/GalleryCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\GalleryCategory;

class GalleryCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = GalleryCategory::all();
        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'description'=>'required'
        ]);

        $gallery_category = new GalleryCategory([
            'name' => $request->get('name'),
            'description' => $request->get('description')
        ]);
        $gallery_category->save();
        return redirect('/admin/gallery')->with('success', 'New category saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = GalleryCategory::find($id);
        return view('category.edit', compact('category'));   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'=>'required',
            'description'=>'required'
        ]);

        $category = GalleryCategory::find($id);
        $category->name =  $request->get('name');
        $category->description = $request->get('description');
        $category->save();

        return redirect('/admin/gallery')->with('success', 'Category updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = GalleryCategory::find($id);
        $category->delete();

        return redirect('/admin/gallery')->with('success', 'Category deleted!');
    }
}

app/Http/Controllers/ApiGalleryController.php
<?php

namespace App\Http\Controllers;

use App\GalleryCategory;
use App\Helpers\FlickrHelper;

class ApiGalleryController extends Controller
{
    /**
     * @param $id category ID
     * @return array
     */
    public function show($id, $page)
    {
        $category = GalleryCategory::find($id);

        $results = FlickrHelper::getSearchResults($category->name, $page);

        $next_page = ($results->photos['pages'] > $results->photos['page'] ? $results->photos['page'] + 1 : false);
       
        $response = [
            'category' => $category->name,
            'next_page' => $next_page,
            'photos' => []
        ];

        foreach ($results->photos['photo'] as $photo) {
            if ($photo['farm'] != 0) {
                $urls = FlickrHelper::generatePhotoSrc($photo);
                $title = $photo['title'];
                $response['photos'][] = [
                    'id' => $photo['id'],
                    'imageUrls' => $urls,
                    'title' => $title,
                ];
            }
        }

        return $response;
    }

    /**
     * @param $id photo ID
     * @return array
     */
    public function photoInfo($photoId)
    {
        $result = FlickrHelper::getPhotoInfo($photoId);
        $response = [
            'id' => $result->photo['id'],
            'imageUrls' => FlickrHelper::generatePhotoSrc($result->photo),
            'title' => $result->photo['title']['_content'],
            'description' => $result->photo['description']['_content'],
            'owner' => $result->photo['owner'],
            'dates' => $result->photo['dates']
        ];

        return $response;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\GalleryCategory;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $categories = GalleryCategory::all();
        return view('gallery.index', compact('categories')); 
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Flickr App') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Flickr Admin') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <main class="py-4">
                @yield('main')
            </main>
        </div>
    </div>
</body>
</html>

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
    <title>Document</title>
</head>
<body>
    <div class="container">
        @yield('main')
      </div>

      <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/category/create.blade.php
@extends('admin')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="title">Add new category</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('gallery.store') }}">
          @csrf
          <div class="form-group">    
              <label for="name">Category Name:</label>
              <input type="text" class="form-control" name="name" value="{{ old('name') }}"/>
          </div>

          <div class="form-group">
              <label for="description">Category Description:</label>
              <textarea class="form-control" name="description">{{ old('description') }}</textarea>
          </div>
          <button type="submit" class="btn btn-primary">Add Category</button>
          <a href="{{ route('gallery.index') }}" class="btn btn-link">Back</a>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/category/edit.blade.php
@extends('admin') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="title">Update Category</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('gallery.update', $category->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">
                <label for="name">Category Name:</label>
                <input type="text" class="form-control" name="name" value={{ $category->name }} />
            </div>
            <div class="form-group">
                <label for="description">Category Description:</label>
                <textarea class="form-control" name="description">{{ $category->description }} </textarea>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
            <a href="{{ route('gallery.index') }}" class="btn btn-link">Back</a>
        </form>
    </div>
</div>
@endsection

resources/views/category/index.blade.php
@extends('admin')

@section('main')
<div class="row">
    <div class="col-sm-12">
        <h1 class="title">Categories</h1>    
    <table class="table table-striped">
        <thead>
            <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Description</td>
            <td colspan = 2>Actions</td>
            </tr>
        </thead>
        <tbody>
            @foreach($categories as $category)
            <tr>
                <td>{{$category->id}}</td>
                <td>{{$category->name}}</td>
                <td>{{$category->description}}</td>
                
                <td>
                    <a href="{{ route('gallery.edit',$category->id)}}" class="btn btn-primary">Edit</a>
                </td>
                <td>
                    <form action="{{ route('gallery.destroy', $category->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div>

    <div class="col-sm-12">
    @if(session()->get('success'))
        <div class="alert alert-success">
        {{ session()->get('success') }}  
        </div>
    @endif
    </div>

    <div>
        <a style="margin: 19px;" href="{{ route('gallery.create')}}" class="btn btn-primary">New Category</a>
    </div>

</div>
@endsection

resources/views/gallery/index.blade.php
@extends('template')

@section('main')


@if( count($categories) == 0)

<div class="row">
    <div class="col-md-12">
        <h1>Service not available. </h1>
        <div class="alert alert-danger">
            <strong>Error!</strong> No photo category available. Please contact the admin.
        </div>
    </div>
</div>

@else

<div class="row">
    <div class="col-sm-12 text-center gallery-title">
        <h2>
            <span class="category-title"></span> Photo Gallery
        </h2>
    </div>
</div>

<div class="row">

    <div class="col-md-3 col-lg-3 hidden-xs hidden-sm ">
        <div class="list-group ">
            <a href="#" class="list-group-item disabled">
                <strong>Select Category</strong>
            </a>
            @foreach ($categories as $category)
            <a href="#{{ $category->id }}" class="list-group-item category-item" data-category-id="{{ $category->id }}">{{ $category->name }}</a>
            @endforeach
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3 visible-xs visible-sm">
        <div class="form-group">
            <label class="control-label">Select Category</label>
            <select class="form-control" id="select-category-item">
                @foreach ($categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }} </option>
                @endforeach
            </select>
        </div>    
    </div>

    <div class="col-xs-12  col-sm-12 col-md-9 col-lg-9">
        <div id="result-container">
            <!-- gallery list -->
            <div id="result-list">
                <div id="images"></div>
                <div class="clearfix"></div>
                <div class="col-md-12">
                    <button class="btn btn-default btn-block" id="show-more" data-next-page="1">Show more</button>
                </div>
            </div>

            <!-- ./gallery list -->

            <!-- photo details -->
            <div id="photo-info">
                <i class="icon glyphicon glyphicon-remove" id="close-selected"></i>
                <div class="col-md-8">
                    <img src="#" class="center-block img-responsive block" id="photo-selected"/>
                </div>
                <div class="col-md-4">
                    <h4 id="photo-title"></h4>
                    <small class="text-muted">
                        <img src="" width="25" id="photo-author-img" height="25" class="img-circle">
                        <strong id="photo-author"></strong> 
                    </small>
                    <p class="text-muted" id="photo-description"></p>
                </div>
            </div>
            <!-- ./photo details -->
            
            <!-- loader -->
            <div id="loading">
                <div class="col-md-12">
                    <small class="text-muted">Loading, please wait...</small>
                </div>
            </div>
            <!-- ./loader -->

            <!-- error -->
            <div id="error">
                <div class="col-md-12">
                    <strong>An error occured. Please try again.</strong>
                </div>
            </div>
            <!-- error -->
            <div class="clearfix"></div>
        </div>
    </div>
</div>
@endif

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/template.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{{URL::asset('css/flickr.css')}}" />

    <title>Flickr App</title>
</head>
<body>
    <div class="container">
        @yield('main')
      </div>
      
      <!-- minified jquery -->
      <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      
      <!-- custom script -->
      <script type="text/javascript" src="{{URL::asset('js/flickr.js')}}"></script>
 
        
</body>
</html>